#define BAT_LOW_LED_DIR(DIR) SET(DDRA._BV(PA4).DIR)

#define BAR_LOW_LED(STATE) SET(PORTA._BV(PA4).~STATE)

#define LCD_DATA_COMMAND(STATE) SET(PORTA._BV(PA6).STATE)
#define LCD_CS0(STATE) SET(PORTA._BV(PA5).~STATE)
#define LCD_BACKLIGHT(STATE) SET(PORTD._BV(PD4).STATE)
#define LCD_RESET(STATE) SET(PORTD._BV(PD3).~STATE)
#define LCD_MOSI(STATE) SET(PORTB._PB5.STATE)
#define LCD_SCK(STATE) SET(PORTB._BV(PB7).STATE)

#define LCD_DATA_COMMAND_DIR(DIR) SET(DDRA._BV(PA6).DIR)
#define LCD_CS0_DIR(DIR) SET(PORTA._BV(PA5).DIR)
#define LCD_BACKLIGHT_DIR(DIR) SET(PORTD._BV(PD4).DIR)
#define LCD_RESET_DIR(DIR) SET(PORTD._BV(PD3).DIR)
#define LCD_MOSI_(DIR) SET(PORTB._PB5.DIR)
#define LCD_SCK_DIR(DIR) SET(PORTB._BV(PB7).DIR)
